<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="12" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="263079" started-at="2014-05-09T07:33:01Z" finished-at="2014-05-09T07:37:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="263079" started-at="2014-05-09T07:33:01Z" finished-at="2014-05-09T07:37:24Z">
      <class name="com.genwi.refreshAPITesting">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="beforeClass" is-config="true" duration-ms="6058" started-at="2014-05-09T13:03:01Z" finished-at="2014-05-09T13:03:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="mCMSLogin()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="mCMSLogin" duration-ms="4332" started-at="2014-05-09T13:03:07Z" finished-at="2014-05-09T13:03:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mCMSLogin -->
        <test-method status="PASS" signature="launchApp()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="launchApp" duration-ms="29105" started-at="2014-05-09T13:03:11Z" finished-at="2014-05-09T13:03:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method status="PASS" signature="addCategory()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="addCategory" duration-ms="22407" started-at="2014-05-09T13:03:40Z" finished-at="2014-05-09T13:04:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCategory -->
        <test-method status="PASS" signature="editCategoryTitle()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="editCategoryTitle" duration-ms="12937" started-at="2014-05-09T13:04:03Z" finished-at="2014-05-09T13:04:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editCategoryTitle -->
        <test-method status="FAIL" signature="addPost()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="addPost" duration-ms="22702" started-at="2014-05-09T13:04:15Z" finished-at="2014-05-09T13:04:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.genwi.refreshAPITesting.addPost(refreshAPITesting.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPost -->
        <test-method status="FAIL" signature="editPost()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="editPost" duration-ms="32584" started-at="2014-05-09T13:04:38Z" finished-at="2014-05-09T13:05:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.genwi.refreshAPITesting.editPost(refreshAPITesting.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editPost -->
        <test-method status="PASS" signature="addFeed()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="addFeed" duration-ms="28227" started-at="2014-05-09T13:05:11Z" finished-at="2014-05-09T13:05:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addFeed -->
        <test-method status="PASS" signature="deleteExistingCategory()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="deleteExistingCategory" duration-ms="21587" started-at="2014-05-09T13:05:39Z" finished-at="2014-05-09T13:06:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteExistingCategory -->
        <test-method status="FAIL" signature="DeletePost()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="DeletePost" duration-ms="21318" started-at="2014-05-09T13:06:01Z" finished-at="2014-05-09T13:06:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.genwi.refreshAPITesting.DeletePost(refreshAPITesting.java:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeletePost -->
        <test-method status="PASS" signature="createTemplateAssigntoPost()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="createTemplateAssigntoPost" duration-ms="36512" started-at="2014-05-09T13:06:22Z" finished-at="2014-05-09T13:06:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTemplateAssigntoPost -->
        <test-method status="PASS" signature="editPostAssignDiffTemplate()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="editPostAssignDiffTemplate" duration-ms="17396" started-at="2014-05-09T13:06:58Z" finished-at="2014-05-09T13:07:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editPostAssignDiffTemplate -->
        <test-method status="PASS" signature="deleteTemplate()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="deleteTemplate" duration-ms="7764" started-at="2014-05-09T13:07:16Z" finished-at="2014-05-09T13:07:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteTemplate -->
        <test-method status="PASS" signature="afterclass()[pri:0, instance:com.genwi.refreshAPITesting@5bf9e31e]" name="afterclass" is-config="true" duration-ms="93" started-at="2014-05-09T13:07:24Z" finished-at="2014-05-09T13:07:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterclass -->
      </class> <!-- com.genwi.refreshAPITesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
